# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de4c89ad86befd068668edb222ddd4ab28c8dba5717c6233a93f15f08926e875c914901b279634f20f4cb2b5d86c6be77a16db19e99d63b241f7c82491d38de6

test:
  secret_key_base: 7a9bd7754b08a8dcc0c7f56f69caa75e1cdcc7e047c103c69568527317f87bdbc5eb87a5a694648a97e229f9e0cdb7f12aaa07e883b2f8abce04068f7330b08a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
